export const GET_DATA = "GET_DATA"
export const INCREMENT = "INCREMENT";
export const DECREMENT = "DECREMENT";
export const SET_CURRENT_QUESTION = "SET_CURRENT_QUESTION";
export const SET_CURRENT_ANSWER_OPTIONS = 'SET_CURRENT_ANSWER_OPTIONS';
export const ADD_USER_INPUT = "ADD_USER_INPUT";
export const CALCULATE_PERCENT = "CALCULATE_PERCENT";
export const SET_LOADING = "SET_LOADING"

